### PR TITLE
Remove curly brackets once it did not has been opened

### PR DESCRIPTION
**Pull request by lucasprag**
Again, I just want to help you guys.

Thanks :smile:

### CODE REVIEW

**Comment by Lucasosf** [comment]
ping @stubailo @hshoff

**Comment by lucasprag** [comment]
ping @stubailo @hshoff

**Comment by hshoff** [comment]
Hi @lucasprag I work on the [airbnb/javascript](http://github.com/airbnb/javascript) project and we encourage forks such as meteor/javascript, but I am not involved with this project.

That said, LGTM.

**Comment by lucasprag** [comment]
I guess this project is abandoned =(

**Pull request closed without merging**
