### PR TITLE
Fix javascript highlight blocks on readme.md

### PR DESCRIPTION
**Pull request by lucasprag**
I just want to help you guys.

You can preview the javascript highlight blocks properly working on https://github.com/lucasprag/javascript

Thanks

### CODE REVIEW

**Comment by Lucasosf** [comment]
ping @stubailo @hshoff

**Comment by lucasprag** [comment]
ping @stubailo @hshoff

**Comment by gehrhorn** [comment]
+1 on this. I was going to fix this today and saw that there's a pending PR.

**Comment by lucasprag** [comment]
I guess this project is abandoned. =(

**Comment by gehrhorn** [comment]
@lucasprag, I'd reopen it. If someone comes back to it one day it would be helpful to know what is still open.

**Pull request closed without merging**
